#! /bin/sh
# /etc/init.d/bela
#

# Some things that run always
# ...nothing to do here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Adding Bela PRU Overlay..."
    echo BB-BONE-PRU-BELA > /sys/devices/bone_capemgr.9/slots
    echo "Adding Bela Audio Cape Overlay..."
    echo BB-BONE-BAREAUDI-02 > /sys/devices/bone_capemgr.9/slots
    cd /root
    sh Bela_startup.sh
    sh Bela_node.sh
    ;;
  stop)
    cd /root/Bela && make stop
    ;;
  *)
    echo "Usage: /etc/init.d/bela {start|stop}"
    exit 1
    ;;
esac

exit 0
