export var Bela: string;
export var webserver_root: string;
export var projects: string;
export var uploads: string;
export var examples: string;
export var libraries: string;
export var gui: string;
export var exampleTempProject: string;
export var media: string;
export var templates: string;
export var ide_settings: string;
export var startup_env: string;
export var lockfile: string;
export var xenomai_stat: string;
export var update: string;
export var update_backup: string;
export var update_log: string;
export var tmp: string;
set_Bela("/root/Bela/");
export function set_Bela(new_path: string){
	Bela = (new_path.trim() + '/').replace(/\/\//, '/'); // ensure it ends with a trailing slash
	webserver_root = Bela+'IDE/public/';
	projects = Bela+'projects/';
	uploads = Bela+'uploads/';
	examples = Bela+'examples/';
	libraries = Bela+'libraries/';
	gui = webserver_root+'gui/';
	exampleTempProject = projects+'exampleTempProject/';
	media = Bela+'IDE/public/media/';
	templates = Bela+'IDE/templates/';
	ide_settings = Bela+'IDE/settings.json';
	startup_env = '/opt/Bela/startup_env';
	lockfile = Bela+'IDE/.lockfile';
	xenomai_stat = '/proc/xenomai/sched/stat';
	update = Bela+'updates/';
	update_backup = Bela+'../_BelaUpdateBackup/updates/';
	update_log = Bela+'../update.log';
	tmp = "/tmp/";
};
export function set_xenomai_stat(new_path: string){ xenomai_stat = new_path; };
