#! /bin/sh
# /etc/init.d/bela
#

# Some things that run always
# ...nothing to do here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Adding Bela Overlay..."
    echo BELA > /sys/devices/platform/bone_capemgr/slots
    echo "Enabling interface and functional clock of McASP..."
    /root/Bela/resources/bin/devmem2 0x44E00034 w 0x30002 >> /dev/null
    cd /root
    sh Bela_startup.sh
    sh Bela_node.sh
    ;;
  stop)
    cd /root/Bela && make stop
    ;;
  *)
    echo "Usage: /etc/init.d/bela {start|stop}"
    exit 1
    ;;
esac

exit 0
